import sys
sys.path.insert(0, '.')
from alvz.core.lexer import Lexer
from alvz.core.parser import Parser
from alvz.core.wasm_compiler import WasmCompiler, _GET_LOCAL, _I32, OpCode, _SET_LOCAL

codigo = '42'
lexer = Lexer(codigo)
tokens = lexer.tokenize()
parser = Parser(tokens)
bc, consts, lm, funcs = parser.compile()

# Monkey-patch _check_op to track sizes
original_check = WasmCompiler._check_op
handler_sizes = []
handler_names = []

def tracking_check(self, opcode, handler_bytes):
    result = original_check(self, opcode, handler_bytes)
    # Measure the generated bytes from result
    nf = len(result)
    handler_sizes.append(nf)
    handler_names.append(f"{opcode} ({int(opcode)})")
    return result

WasmCompiler._check_op = tracking_check

compiler = WasmCompiler(bc, consts, funcs, lm)
wasm_bytes = compiler.compile()

# Restore
WasmCompiler._check_op = original_check

# Calculate offsets
# Init code:
# $ip=0 (4b)
# block 40 (2b) + loop 40 (2b)
# load op ~10b
init_size = 4 + 2 + 2 + 10  # ~18

offset = init_size
print(f"Init setup: {offset} bytes")
for i, (name, size) in enumerate(zip(handler_names, handler_sizes)):
    end = offset + size
    # Check if error offset 5640 falls in this handler
    # Error at 5640 from file start, which is code_start + 5640 - ?
    # code_start = file offset of code section + section header + content header
    # We know: code content at 208, count=1 at 208, body_size LEB128 at 209
    # body at ~211, local decls take some bytes
    # Let's compute: body_start should be where body content starts
    # body_start = 208 + 1 + body_size_leb_bytes 
    # body_size_leb_bytes for 11194 = 2 bytes (ba 57)
    # body_start = 208 + 1 + 2 = 211
    # Then local decls... let me just use the known code_start = 211 + something
    file_start_of_code = 5640 - 3559  # from earlier: code_off=3559 maps to file_off=3791
    # Actually from earlier: for the OLD error at 3791, code_off was 3559
    # 3791 - 3559 = 232 = offset from file start to code start
    # So code_start_file_offset = 232
    # Actually that can't be right since the code section starts at 205
    # Let me use the known data: body_start=211, code_start~232
    code_start_file = 232  # approximate
    
    err_from_code_start = 5640 - 232  # file_off - code_start_file_off
    
    if offset <= err_from_code_start < end:
        print(f">>> ERROR HERE: {name} at range [{offset}:{end}]")
        print(f"  Error at +{err_from_code_start - offset} from handler start")
    offset = end

print(f"\nTotal code bytes through handlers: {offset}")
print(f"Error at code offset: {err_from_code_start}")
